# Generated by Django 5.0.6 on 2024-05-31 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_1', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 1')),
                ('mark_2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 2')),
                ('mark_3', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 3')),
            ],
            options={
                'verbose_name': 'Trimestre',
                'verbose_name_plural': 'Trimestres',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Promedio')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Curso')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('trimester_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_1', to='core.trimester', verbose_name='Trimestre 1')),
                ('trimester_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_2', to='core.trimester', verbose_name='Trimestre 2')),
                ('trimester_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_3', to='core.trimester', verbose_name='Trimestre 3')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
