# Generated by Django 5.0.6 on 2024-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_mark_average_remove_mark_trimester_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trimester',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester1_average',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester1_mark1',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester1_mark2',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester1_mark3',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester2_average',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester2_mark1',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester2_mark2',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester2_mark3',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester3_average',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester3_mark1',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester3_mark2',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='trimester3_mark3',
        ),
        migrations.AddField(
            model_name='mark',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Promedio'),
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 1'),
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 2'),
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 3'),
        ),
    ]
