# Generated by Django 5.0.6 on 2024-06-04 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_attendance_course_attendance_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia', verbose_name='Materia'),
        ),
    ]
