# Generated by Django 5.0.6 on 2024-06-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_attendance_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='average_trimester_1',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='average_trimester_2',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='average_trimester_3',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='final_average',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_1_trimester_1',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_1_trimester_2',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_1_trimester_3',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_2_trimester_1',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_2_trimester_2',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_2_trimester_3',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_3_trimester_1',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_3_trimester_2',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_3_trimester_3',
        ),
        migrations.AddField(
            model_name='mark',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Promedio'),
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 1'),
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 2'),
        ),
        migrations.AddField(
            model_name='mark',
            name='mark_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota 3'),
        ),
    ]
