# Generated by Django 5.0.6 on 2024-08-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_mark_average_trimester_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='activate_grading',
            field=models.BooleanField(default=True, verbose_name='Activar Calificaciones'),
        ),
    ]
