# Generated by Django 5.0.6 on 2024-08-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_materia_activate_grading'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_add_notes', models.BooleanField(default=True)),
            ],
        ),
    ]
