# Generated by Django 5.0.6 on 2024-08-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_globalconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Descripción'),
        ),
    ]
