# Generated by Django 5.0.6 on 2024-09-17 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_course_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=4, unique=True, verbose_name='Código Único')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('teacher', models.ForeignKey(limit_choices_to={'groups__name': 'profesores'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Asistencia del Profesor',
                'verbose_name_plural': 'Asistencias de los Profesores',
            },
        ),
    ]
