# Generated by Django 5.0.6 on 2024-09-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_teacherattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
