# Generated by Django 5.0.6 on 2024-09-18 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_citeacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado en')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.citeacher', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Asistencia de Profesor',
                'verbose_name_plural': 'Asistencias de Profesores',
            },
        ),
    ]
