# Generated by Django 5.0.6 on 2024-10-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
