# Generated by Django 5.0.6 on 2024-11-19 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Primer trimestre'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Segundo trimestre'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tercer trimestre'),
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('is_approved', models.BooleanField()),
                ('final_average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Promedio Final')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('detailed_grades', models.JSONField(blank=True, null=True, verbose_name='Notas Detalladas')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Curso')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'estudiantes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Historial de Estudiante',
                'verbose_name_plural': 'Historial de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_documents/', verbose_name='Documento')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.studenthistory', verbose_name='Historial')),
            ],
        ),
    ]
