# Generated by Django 5.0.6 on 2024-11-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_mark_mark_1_alter_mark_mark_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_evolution_view', models.BooleanField(default=True)),
            ],
        ),
    ]
