# Generated by Django 5.0.6 on 2024-11-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_adminsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSettings',
        ),
    ]
