# Generated by Django 5.0.6 on 2024-11-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_delete_adminsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_consult_evolution', models.BooleanField(default=True)),
            ],
        ),
    ]
