# Generated by Django 5.0.6 on 2024-11-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_globalsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='allow_view_evolution',
            field=models.BooleanField(default=True),
        ),
    ]
