# Generated by Django 5.0.6 on 2024-11-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_delete_globalsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Promedio'),
        ),
    ]
