# Generated by Django 5.0.6 on 2024-11-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_mark_average'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcludedStudent',
        ),
    ]
