# Generated by Django 5.0.6 on 2024-12-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_teacherschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('file', models.FileField(upload_to='books/', verbose_name='Archivo')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core.level', verbose_name='Nivel')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherSchedule',
        ),
    ]
