# Generated by Django 5.0.6 on 2024-12-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_level_book_delete_teacherschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
