# Generated by Django 5.0.6 on 2024-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_delete_book_delete_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('published_date', models.DateField(verbose_name='Fecha de publicación')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
            ],
        ),
    ]
