# Generated by Django 5.0.6 on 2024-12-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
