# Generated by Django 5.0.6 on 2024-08-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_add_notes',
            field=models.BooleanField(default=False),
        ),
    ]
