# Generated by Django 5.0.6 on 2024-08-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_allow_add_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='allow_add_notes',
        ),
    ]
