# Generated by Django 5.0.6 on 2024-08-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_allow_add_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_by_admin',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Creado por admin'),
        ),
    ]
