# Generated by Django 5.0.6 on 2024-09-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_create_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Código Único'),
        ),
    ]
